<?php
/**
 * ObjsEnterpriseUserTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ObjsEnterpriseUserTest Class Doc Comment
 *
 * @category    Class
 * @description ObjsEnterpriseUser
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ObjsEnterpriseUserTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ObjsEnterpriseUser"
     */
    public function testObjsEnterpriseUser()
    {
    }

    /**
     * Test attribute "enterprise_id"
     */
    public function testPropertyEnterpriseId()
    {
    }

    /**
     * Test attribute "enterprise_name"
     */
    public function testPropertyEnterpriseName()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "is_admin"
     */
    public function testPropertyIsAdmin()
    {
    }

    /**
     * Test attribute "is_owner"
     */
    public function testPropertyIsOwner()
    {
    }

    /**
     * Test attribute "teams"
     */
    public function testPropertyTeams()
    {
    }
}
