<?php
/**
 * ObjsCommentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ObjsCommentTest Class Doc Comment
 *
 * @category    Class
 * @description ObjsComment
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ObjsCommentTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ObjsComment"
     */
    public function testObjsComment()
    {
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "is_intro"
     */
    public function testPropertyIsIntro()
    {
    }

    /**
     * Test attribute "is_starred"
     */
    public function testPropertyIsStarred()
    {
    }

    /**
     * Test attribute "num_stars"
     */
    public function testPropertyNumStars()
    {
    }

    /**
     * Test attribute "pinned_info"
     */
    public function testPropertyPinnedInfo()
    {
    }

    /**
     * Test attribute "pinned_to"
     */
    public function testPropertyPinnedTo()
    {
    }

    /**
     * Test attribute "reactions"
     */
    public function testPropertyReactions()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {
    }
}
