<?php
/**
 * ObjsFileTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ObjsFileTest Class Doc Comment
 *
 * @category    Class
 * @description ObjsFile
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ObjsFileTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ObjsFile"
     */
    public function testObjsFile()
    {
    }

    /**
     * Test attribute "channels"
     */
    public function testPropertyChannels()
    {
    }

    /**
     * Test attribute "comments_count"
     */
    public function testPropertyCommentsCount()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "display_as_bot"
     */
    public function testPropertyDisplayAsBot()
    {
    }

    /**
     * Test attribute "editable"
     */
    public function testPropertyEditable()
    {
    }

    /**
     * Test attribute "editor"
     */
    public function testPropertyEditor()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "external_type"
     */
    public function testPropertyExternalType()
    {
    }

    /**
     * Test attribute "external_url"
     */
    public function testPropertyExternalUrl()
    {
    }

    /**
     * Test attribute "filetype"
     */
    public function testPropertyFiletype()
    {
    }

    /**
     * Test attribute "groups"
     */
    public function testPropertyGroups()
    {
    }

    /**
     * Test attribute "has_rich_preview"
     */
    public function testPropertyHasRichPreview()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "image_exif_rotation"
     */
    public function testPropertyImageExifRotation()
    {
    }

    /**
     * Test attribute "ims"
     */
    public function testPropertyIms()
    {
    }

    /**
     * Test attribute "is_external"
     */
    public function testPropertyIsExternal()
    {
    }

    /**
     * Test attribute "is_public"
     */
    public function testPropertyIsPublic()
    {
    }

    /**
     * Test attribute "is_starred"
     */
    public function testPropertyIsStarred()
    {
    }

    /**
     * Test attribute "is_tombstoned"
     */
    public function testPropertyIsTombstoned()
    {
    }

    /**
     * Test attribute "last_editor"
     */
    public function testPropertyLastEditor()
    {
    }

    /**
     * Test attribute "mimetype"
     */
    public function testPropertyMimetype()
    {
    }

    /**
     * Test attribute "mode"
     */
    public function testPropertyMode()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "num_stars"
     */
    public function testPropertyNumStars()
    {
    }

    /**
     * Test attribute "original_h"
     */
    public function testPropertyOriginalH()
    {
    }

    /**
     * Test attribute "original_w"
     */
    public function testPropertyOriginalW()
    {
    }

    /**
     * Test attribute "permalink"
     */
    public function testPropertyPermalink()
    {
    }

    /**
     * Test attribute "permalink_public"
     */
    public function testPropertyPermalinkPublic()
    {
    }

    /**
     * Test attribute "pinned_info"
     */
    public function testPropertyPinnedInfo()
    {
    }

    /**
     * Test attribute "pinned_to"
     */
    public function testPropertyPinnedTo()
    {
    }

    /**
     * Test attribute "pretty_type"
     */
    public function testPropertyPrettyType()
    {
    }

    /**
     * Test attribute "public_url_shared"
     */
    public function testPropertyPublicUrlShared()
    {
    }

    /**
     * Test attribute "reactions"
     */
    public function testPropertyReactions()
    {
    }

    /**
     * Test attribute "shares"
     */
    public function testPropertyShares()
    {
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }

    /**
     * Test attribute "source_team"
     */
    public function testPropertySourceTeam()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "thumb_1024"
     */
    public function testPropertyThumb1024()
    {
    }

    /**
     * Test attribute "thumb_1024_h"
     */
    public function testPropertyThumb1024H()
    {
    }

    /**
     * Test attribute "thumb_1024_w"
     */
    public function testPropertyThumb1024W()
    {
    }

    /**
     * Test attribute "thumb_160"
     */
    public function testPropertyThumb160()
    {
    }

    /**
     * Test attribute "thumb_360"
     */
    public function testPropertyThumb360()
    {
    }

    /**
     * Test attribute "thumb_360_h"
     */
    public function testPropertyThumb360H()
    {
    }

    /**
     * Test attribute "thumb_360_w"
     */
    public function testPropertyThumb360W()
    {
    }

    /**
     * Test attribute "thumb_480"
     */
    public function testPropertyThumb480()
    {
    }

    /**
     * Test attribute "thumb_480_h"
     */
    public function testPropertyThumb480H()
    {
    }

    /**
     * Test attribute "thumb_480_w"
     */
    public function testPropertyThumb480W()
    {
    }

    /**
     * Test attribute "thumb_64"
     */
    public function testPropertyThumb64()
    {
    }

    /**
     * Test attribute "thumb_720"
     */
    public function testPropertyThumb720()
    {
    }

    /**
     * Test attribute "thumb_720_h"
     */
    public function testPropertyThumb720H()
    {
    }

    /**
     * Test attribute "thumb_720_w"
     */
    public function testPropertyThumb720W()
    {
    }

    /**
     * Test attribute "thumb_80"
     */
    public function testPropertyThumb80()
    {
    }

    /**
     * Test attribute "thumb_800"
     */
    public function testPropertyThumb800()
    {
    }

    /**
     * Test attribute "thumb_800_h"
     */
    public function testPropertyThumb800H()
    {
    }

    /**
     * Test attribute "thumb_800_w"
     */
    public function testPropertyThumb800W()
    {
    }

    /**
     * Test attribute "thumb_960"
     */
    public function testPropertyThumb960()
    {
    }

    /**
     * Test attribute "thumb_960_h"
     */
    public function testPropertyThumb960H()
    {
    }

    /**
     * Test attribute "thumb_960_w"
     */
    public function testPropertyThumb960W()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "updated"
     */
    public function testPropertyUpdated()
    {
    }

    /**
     * Test attribute "url_private"
     */
    public function testPropertyUrlPrivate()
    {
    }

    /**
     * Test attribute "url_private_download"
     */
    public function testPropertyUrlPrivateDownload()
    {
    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {
    }

    /**
     * Test attribute "user_team"
     */
    public function testPropertyUserTeam()
    {
    }

    /**
     * Test attribute "username"
     */
    public function testPropertyUsername()
    {
    }
}
