<?php
/**
 * ChannelsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ChannelsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ChannelsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for channelsArchive
     *
     * .
     *
     */
    public function testChannelsArchive()
    {
    }

    /**
     * Test case for channelsCreate
     *
     * .
     *
     */
    public function testChannelsCreate()
    {
    }

    /**
     * Test case for channelsHistory
     *
     * .
     *
     */
    public function testChannelsHistory()
    {
    }

    /**
     * Test case for channelsInfo
     *
     * .
     *
     */
    public function testChannelsInfo()
    {
    }

    /**
     * Test case for channelsInvite
     *
     * .
     *
     */
    public function testChannelsInvite()
    {
    }

    /**
     * Test case for channelsJoin
     *
     * .
     *
     */
    public function testChannelsJoin()
    {
    }

    /**
     * Test case for channelsKick
     *
     * .
     *
     */
    public function testChannelsKick()
    {
    }

    /**
     * Test case for channelsLeave
     *
     * .
     *
     */
    public function testChannelsLeave()
    {
    }

    /**
     * Test case for channelsList
     *
     * .
     *
     */
    public function testChannelsList()
    {
    }

    /**
     * Test case for channelsMark
     *
     * .
     *
     */
    public function testChannelsMark()
    {
    }

    /**
     * Test case for channelsRename
     *
     * .
     *
     */
    public function testChannelsRename()
    {
    }

    /**
     * Test case for channelsReplies
     *
     * .
     *
     */
    public function testChannelsReplies()
    {
    }

    /**
     * Test case for channelsSetPurpose
     *
     * .
     *
     */
    public function testChannelsSetPurpose()
    {
    }

    /**
     * Test case for channelsSetTopic
     *
     * .
     *
     */
    public function testChannelsSetTopic()
    {
    }

    /**
     * Test case for channelsUnarchive
     *
     * .
     *
     */
    public function testChannelsUnarchive()
    {
    }
}
