<?php
/**
 * ConversationsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ConversationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConversationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for conversationsArchive
     *
     * .
     *
     */
    public function testConversationsArchive()
    {
    }

    /**
     * Test case for conversationsClose
     *
     * .
     *
     */
    public function testConversationsClose()
    {
    }

    /**
     * Test case for conversationsCreate
     *
     * .
     *
     */
    public function testConversationsCreate()
    {
    }

    /**
     * Test case for conversationsHistory
     *
     * .
     *
     */
    public function testConversationsHistory()
    {
    }

    /**
     * Test case for conversationsInfo
     *
     * .
     *
     */
    public function testConversationsInfo()
    {
    }

    /**
     * Test case for conversationsInvite
     *
     * .
     *
     */
    public function testConversationsInvite()
    {
    }

    /**
     * Test case for conversationsJoin
     *
     * .
     *
     */
    public function testConversationsJoin()
    {
    }

    /**
     * Test case for conversationsKick
     *
     * .
     *
     */
    public function testConversationsKick()
    {
    }

    /**
     * Test case for conversationsLeave
     *
     * .
     *
     */
    public function testConversationsLeave()
    {
    }

    /**
     * Test case for conversationsList
     *
     * .
     *
     */
    public function testConversationsList()
    {
    }

    /**
     * Test case for conversationsMembers
     *
     * .
     *
     */
    public function testConversationsMembers()
    {
    }

    /**
     * Test case for conversationsOpen
     *
     * .
     *
     */
    public function testConversationsOpen()
    {
    }

    /**
     * Test case for conversationsRename
     *
     * .
     *
     */
    public function testConversationsRename()
    {
    }

    /**
     * Test case for conversationsReplies
     *
     * .
     *
     */
    public function testConversationsReplies()
    {
    }

    /**
     * Test case for conversationsSetPurpose
     *
     * .
     *
     */
    public function testConversationsSetPurpose()
    {
    }

    /**
     * Test case for conversationsSetTopic
     *
     * .
     *
     */
    public function testConversationsSetTopic()
    {
    }

    /**
     * Test case for conversationsUnarchive
     *
     * .
     *
     */
    public function testConversationsUnarchive()
    {
    }
}
